#!/usr/bin/env zsh

filename="${1}"

if [[ -z "${filename}" ]]; then
  echo "ERROR: Need to provide filename."
  exit 1
fi

if [[ ! -f "${filename}" ]]; then
  echo "ERROR: filename '${filename}' does not exist."
  exit 1
fi

echo "Masking external IPs in '${filename}'..."

sed -i -E "s/(0?82|0?81|0?38)\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/[MASKED_IP]/g" ${filename}

echo "Done."
