#!/usr/bin/env zsh

# Configuration
SELF="xyz.hribar.xprotect_forced"
CMD="ServiceStop"
# plistLoc="/Library/LaunchDaemons/${SELF}.plist"

# Our own logging utility
logExec="/usr/local/bin/bhlog"

# --- FUNCTION: _logEvent ---
function _logEvent() {
  local msg="${1}"
  local timestamp

  # 1. Get the timestamp
  timestamp=$(gdate '+%Y-%m-%d %H:%M:%S.%6N')

  # 2. Print to standard out (for debug/console logs)
  echo "[${timestamp}] ${SELF} ${CMD:-Check} [PPID:${$}] ${msg}"

  # 3. Call the logging utility
  if [[ -x "${logExec}" ]]; then
    "${logExec}" "${SELF}" "${CMD:-Check}" "[PPID:${$}] ${msg}"
  fi
}

# --- MAIN EXECUTION ---
# 1. Ask for password upfront
sudo -v

# 2. Stopping service
_logEvent "Stopping service '${SELF}'..."
sudo launchctl bootout system/${SELF} 2>/dev/null || true

_logEvent "✅ Done."
